name: Bug Report
description: Report a bug in Download Manager.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Give a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Give the steps to reproduce the behaviour.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Download Manager Version
      description: Which version of Download Manager are you using?
      placeholder: 'Version: 1.0.0.0'
    validations:
      required: true
  - type: input
    attributes:
      label: Windows Version
      description: Which version of Windows are you using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> and copy.
      placeholder: e.g. Windows 11 21H2 22000.194
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the bug report.
