name: Feature Request
description: Suggest an idea for Download Manager.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What's the Problem?
      description: If your feature request is related to a problem, describe it clearly.
  - type: textarea
    attributes:
      label: Solution/Idea
      description: Describe your solution/idea.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Download Manager Version
      description: Which version of Download Manager are you using?
      placeholder: 'Version: 1.0.0.0'
  - type: input
    attributes:
      label: Windows Version
      description: Which version of Windows are you using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> and copy.
      placeholder: e.g. Windows 11 21H2 22000.194
  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the feature request.
