name: Security Vulnerability
description: Report a security vulnerability in Download Manager.
labels: [vulnerability]
body:
  - type: textarea
    attributes:
      label: Describe the vulnerability
      description: Give a clear and concise description of what the vulnerability is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Fix or Recommendation
      description: Give a possible fix for the vulnerability or give a recommendation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Please attach images and videos/GIFs or a link to show where the vulnerability is.
    validations:
      required: true
  - type: input
    attributes:
      label: CVE ID
      description: Please enter the CVE ID of the security vulnerability.
      placeholder: 'CVE-2022-29117'
  - type: input
    id: version
    attributes:
      label: Download Manager Version
      description: Which version of Download Manager are you using?
      placeholder: 'Version: 1.0.0.0'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comments
      description: Additional information or comments about the security vulnerability.
