name: "Build Artifacts"

on:
  push:
  workflow_dispatch:

jobs:
  analyze:
    name: Artifacts
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-prerelease: true

    
    - name: Build
      run: MSBuild.exe /p:Configuration=Debug /t:Build
    
    - name: Upload Download Manager Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Download Manager Build
        path: bin/Debug/net6.0-windows10.0.22000.0
